# nelmio_cors:
#     defaults:
#         origin_regex: true
#         allow_origin: ['https//google.com']
#         allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
#         allow_headers: ['Content-Type', 'Authorization']
#         expose_headers: ['Link']
#         max_age: 3600
#     paths:
#         '^/xxx/xx': 
#             allow_origin: ['https//googxle.com']
#             allow_headers: ['X-Custom-Auth']
#             allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
#             max_age: 3600
#             origin_regex: true
